openapi: 3.0.3
info:
  title: Swagger SPA - OpenAPI 3.0
  contact:
    email: ismailrzouki7@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://localhost:8080/api/v1
   
paths:
  /greeting:
    get:
      tags: 
        - Greeting
      operationId: greeting
      summary: Hello world openApi
      responses:
        '200':
          description: Greeting from SPA.
          content:
            text/plain:
              schema:
                type: string
                example: Hallo Developer!
  /user/auth:
    post:
      tags:
        - Authentication
      operationId: auth
      summary: User Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialPayload'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
                example: json
  
  /user/create:
    post:
      tags:
        - Authentication
      operationId: create
      summary: User Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialPayload'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
                example: json
                
components:
  schemas:
    CredentialPayload:
      type: object
      properties:
        email:
          type: string
          example: "ismaa@ecommapp.com"
        password:
          type: string
          example: "plainText"
        returnSecureToken:
          type: boolean
          example: true
